### ISSUE TITLE
Downloading 1.15.2 is not possible using current userdata

### ISSUE THREAD

**Issue by kenoir** [darrelldavis/terraform-aws-minecraft#2]
Mojang seem to have changed where the server JARs can be downloaded from in 1.15. Consequently the mechanism specified in userdata at present does not work.

It seems the way to get the correct version now is by navigating the launch manifest JSON provided:

https://launchermeta.mojang.com/mc/game/version_manifest.json

That is a little annoying (though feasible) to do in a the startup script.

I've solved this in my fork (https://github.com/kenoir/terraform-aws-minecraft/commit/441a14be7dc94d97f5ba7152902c9bb0df45f078) by being more permissive about where to get the server jar from - it is definitely less user friendly though.

What are your thoughts about the direction this should go in?

**Comment by darrelldavis** [comment]
Greetings kenoir! Thanks for pointing this out and I'm humbled you find this project useful. I changed user_data.sh to use 'jq' to parse the version_manifest.json and support any MC version, including "latest". Also created reasonable defaults to all params (vpc, subnet_id, etc) to make this easier and more turn-key. Use 'ref=v1.0' to get the previous version if you still want that one or 'master' to get this updated version. Thanks again and lemme know if you experience any new bugs (I tested but not super thoroughly).
